/*
 * Purview Catalog Service REST API Document
 * Purview Catalog Service is a fully managed cloud service whose users can discover the data sources they need and understand the data sources they find. At the same time, Data Catalog helps organizations get more value from their existing investments. This swagger defines REST API of the Hot Tier of Data Catalog Gen 2.
 *
 * The version of the OpenAPI document: 2020-12-01-preview
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.JsonAtlasTermRelationshipStatus;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for JsonAtlasTermCategorizationHeader
 */
public class JsonAtlasTermCategorizationHeaderTest {
    private final JsonAtlasTermCategorizationHeader model = new JsonAtlasTermCategorizationHeader();

    /**
     * Model tests for JsonAtlasTermCategorizationHeader
     */
    @Test
    public void testJsonAtlasTermCategorizationHeader() {
        // TODO: test JsonAtlasTermCategorizationHeader
    }

    /**
     * Test the property 'categoryGuid'
     */
    @Test
    public void categoryGuidTest() {
        // TODO: test categoryGuid
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'displayText'
     */
    @Test
    public void displayTextTest() {
        // TODO: test displayText
    }

    /**
     * Test the property 'relationGuid'
     */
    @Test
    public void relationGuidTest() {
        // TODO: test relationGuid
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

}
