/*
 * Purview Catalog Service REST API Document
 * Purview Catalog Service is a fully managed cloud service whose users can discover the data sources they need and understand the data sources they find. At the same time, Data Catalog helps organizations get more value from their existing investments. This swagger defines REST API of the Hot Tier of Data Catalog Gen 2.
 *
 * The version of the OpenAPI document: 2020-12-01-preview
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.JsonSavedSearchType;
import org.openapitools.client.model.JsonSearchParameters;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for JsonAtlasUserSavedSearchAllOf
 */
public class JsonAtlasUserSavedSearchAllOfTest {
    private final JsonAtlasUserSavedSearchAllOf model = new JsonAtlasUserSavedSearchAllOf();

    /**
     * Model tests for JsonAtlasUserSavedSearchAllOf
     */
    @Test
    public void testJsonAtlasUserSavedSearchAllOf() {
        // TODO: test JsonAtlasUserSavedSearchAllOf
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'ownerName'
     */
    @Test
    public void ownerNameTest() {
        // TODO: test ownerName
    }

    /**
     * Test the property 'searchParameters'
     */
    @Test
    public void searchParametersTest() {
        // TODO: test searchParameters
    }

    /**
     * Test the property 'searchType'
     */
    @Test
    public void searchTypeTest() {
        // TODO: test searchType
    }

    /**
     * Test the property 'uiParameters'
     */
    @Test
    public void uiParametersTest() {
        // TODO: test uiParameters
    }

}
