/*
 * Purview Catalog Service REST API Document
 * Purview Catalog Service is a fully managed cloud service whose users can discover the data sources they need and understand the data sources they find. At the same time, Data Catalog helps organizations get more value from their existing investments. This swagger defines REST API of the Hot Tier of Data Catalog Gen 2.
 *
 * The version of the OpenAPI document: 2020-12-01-preview
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.JsonFilterCriteria;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for JsonSearchParameters
 */
public class JsonSearchParametersTest {
    private final JsonSearchParameters model = new JsonSearchParameters();

    /**
     * Model tests for JsonSearchParameters
     */
    @Test
    public void testJsonSearchParameters() {
        // TODO: test JsonSearchParameters
    }

    /**
     * Test the property 'attributes'
     */
    @Test
    public void attributesTest() {
        // TODO: test attributes
    }

    /**
     * Test the property 'classification'
     */
    @Test
    public void classificationTest() {
        // TODO: test classification
    }

    /**
     * Test the property 'entityFilters'
     */
    @Test
    public void entityFiltersTest() {
        // TODO: test entityFilters
    }

    /**
     * Test the property 'excludeDeletedEntities'
     */
    @Test
    public void excludeDeletedEntitiesTest() {
        // TODO: test excludeDeletedEntities
    }

    /**
     * Test the property 'includeClassificationAttributes'
     */
    @Test
    public void includeClassificationAttributesTest() {
        // TODO: test includeClassificationAttributes
    }

    /**
     * Test the property 'includeSubClassifications'
     */
    @Test
    public void includeSubClassificationsTest() {
        // TODO: test includeSubClassifications
    }

    /**
     * Test the property 'includeSubTypes'
     */
    @Test
    public void includeSubTypesTest() {
        // TODO: test includeSubTypes
    }

    /**
     * Test the property 'limit'
     */
    @Test
    public void limitTest() {
        // TODO: test limit
    }

    /**
     * Test the property 'offset'
     */
    @Test
    public void offsetTest() {
        // TODO: test offset
    }

    /**
     * Test the property 'query'
     */
    @Test
    public void queryTest() {
        // TODO: test query
    }

    /**
     * Test the property 'tagFilters'
     */
    @Test
    public void tagFiltersTest() {
        // TODO: test tagFilters
    }

    /**
     * Test the property 'termName'
     */
    @Test
    public void termNameTest() {
        // TODO: test termName
    }

    /**
     * Test the property 'typeName'
     */
    @Test
    public void typeNameTest() {
        // TODO: test typeName
    }

}
