/*
 * Purview Catalog Service REST API Document
 * Purview Catalog Service is a fully managed cloud service whose users can discover the data sources they need and understand the data sources they find. At the same time, Data Catalog helps organizations get more value from their existing investments. This swagger defines REST API of the Hot Tier of Data Catalog Gen 2.
 *
 * The version of the OpenAPI document: 2020-12-01-preview
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.client.model.JsonAtlasClassification;
import org.openapitools.client.model.JsonAtlasEntityHeaderAllOf;
import org.openapitools.client.model.JsonAtlasStruct;
import org.openapitools.client.model.JsonAtlasTermAssignmentHeader;
import org.openapitools.client.model.JsonStatus;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for JsonAtlasEntityHeader
 */
public class JsonAtlasEntityHeaderTest {
    private final JsonAtlasEntityHeader model = new JsonAtlasEntityHeader();

    /**
     * Model tests for JsonAtlasEntityHeader
     */
    @Test
    public void testJsonAtlasEntityHeader() {
        // TODO: test JsonAtlasEntityHeader
    }

    /**
     * Test the property 'attributes'
     */
    @Test
    public void attributesTest() {
        // TODO: test attributes
    }

    /**
     * Test the property 'typeName'
     */
    @Test
    public void typeNameTest() {
        // TODO: test typeName
    }

    /**
     * Test the property 'lastModifiedTS'
     */
    @Test
    public void lastModifiedTSTest() {
        // TODO: test lastModifiedTS
    }

    /**
     * Test the property 'classificationNames'
     */
    @Test
    public void classificationNamesTest() {
        // TODO: test classificationNames
    }

    /**
     * Test the property 'classifications'
     */
    @Test
    public void classificationsTest() {
        // TODO: test classifications
    }

    /**
     * Test the property 'displayText'
     */
    @Test
    public void displayTextTest() {
        // TODO: test displayText
    }

    /**
     * Test the property 'guid'
     */
    @Test
    public void guidTest() {
        // TODO: test guid
    }

    /**
     * Test the property 'meaningNames'
     */
    @Test
    public void meaningNamesTest() {
        // TODO: test meaningNames
    }

    /**
     * Test the property 'meanings'
     */
    @Test
    public void meaningsTest() {
        // TODO: test meanings
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

}
