/*
 * Purview Catalog Service REST API Document
 * Purview Catalog Service is a fully managed cloud service whose users can discover the data sources they need and understand the data sources they find. At the same time, Data Catalog helps organizations get more value from their existing investments. This swagger defines REST API of the Hot Tier of Data Catalog Gen 2.
 *
 * The version of the OpenAPI document: 2020-12-01-preview
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.client.model.JsonAtlasClassificationAllOf;
import org.openapitools.client.model.JsonAtlasStruct;
import org.openapitools.client.model.JsonStatus;
import org.openapitools.client.model.JsonTimeBoundary;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for JsonAtlasClassification
 */
public class JsonAtlasClassificationTest {
    private final JsonAtlasClassification model = new JsonAtlasClassification();

    /**
     * Model tests for JsonAtlasClassification
     */
    @Test
    public void testJsonAtlasClassification() {
        // TODO: test JsonAtlasClassification
    }

    /**
     * Test the property 'attributes'
     */
    @Test
    public void attributesTest() {
        // TODO: test attributes
    }

    /**
     * Test the property 'typeName'
     */
    @Test
    public void typeNameTest() {
        // TODO: test typeName
    }

    /**
     * Test the property 'lastModifiedTS'
     */
    @Test
    public void lastModifiedTSTest() {
        // TODO: test lastModifiedTS
    }

    /**
     * Test the property 'entityGuid'
     */
    @Test
    public void entityGuidTest() {
        // TODO: test entityGuid
    }

    /**
     * Test the property 'entityStatus'
     */
    @Test
    public void entityStatusTest() {
        // TODO: test entityStatus
    }

    /**
     * Test the property 'propagate'
     */
    @Test
    public void propagateTest() {
        // TODO: test propagate
    }

    /**
     * Test the property 'removePropagationsOnEntityDelete'
     */
    @Test
    public void removePropagationsOnEntityDeleteTest() {
        // TODO: test removePropagationsOnEntityDelete
    }

    /**
     * Test the property 'validityPeriods'
     */
    @Test
    public void validityPeriodsTest() {
        // TODO: test validityPeriods
    }

    /**
     * Test the property 'source'
     */
    @Test
    public void sourceTest() {
        // TODO: test source
    }

    /**
     * Test the property 'sourceDetails'
     */
    @Test
    public void sourceDetailsTest() {
        // TODO: test sourceDetails
    }

}
