/*
 * Purview Catalog Service REST API Document
 * Purview Catalog Service is a fully managed cloud service whose users can discover the data sources they need and understand the data sources they find. At the same time, Data Catalog helps organizations get more value from their existing investments. This swagger defines REST API of the Hot Tier of Data Catalog Gen 2.
 *
 * The version of the OpenAPI document: 2020-12-01-preview
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.JsonAtlasRelationshipEndDef;
import org.openapitools.client.model.JsonPropagateTags;
import org.openapitools.client.model.JsonRelationshipCategory;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for JsonAtlasRelationshipDefAllOf
 */
public class JsonAtlasRelationshipDefAllOfTest {
    private final JsonAtlasRelationshipDefAllOf model = new JsonAtlasRelationshipDefAllOf();

    /**
     * Model tests for JsonAtlasRelationshipDefAllOf
     */
    @Test
    public void testJsonAtlasRelationshipDefAllOf() {
        // TODO: test JsonAtlasRelationshipDefAllOf
    }

    /**
     * Test the property 'endDef1'
     */
    @Test
    public void endDef1Test() {
        // TODO: test endDef1
    }

    /**
     * Test the property 'endDef2'
     */
    @Test
    public void endDef2Test() {
        // TODO: test endDef2
    }

    /**
     * Test the property 'propagateTags'
     */
    @Test
    public void propagateTagsTest() {
        // TODO: test propagateTags
    }

    /**
     * Test the property 'relationshipCategory'
     */
    @Test
    public void relationshipCategoryTest() {
        // TODO: test relationshipCategory
    }

    /**
     * Test the property 'relationshipLabel'
     */
    @Test
    public void relationshipLabelTest() {
        // TODO: test relationshipLabel
    }

}
