/*
 * Purview Catalog Service REST API Document
 * Purview Catalog Service is a fully managed cloud service whose users can discover the data sources they need and understand the data sources they find. At the same time, Data Catalog helps organizations get more value from their existing investments. This swagger defines REST API of the Hot Tier of Data Catalog Gen 2.
 *
 * The version of the OpenAPI document: 2020-12-01-preview
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.JsonAtlasStruct;
import org.openapitools.client.model.JsonStatus;
import org.openapitools.client.model.JsonStatusAtlasRelationship;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for JsonAtlasRelatedObjectIdAllOf
 */
public class JsonAtlasRelatedObjectIdAllOfTest {
    private final JsonAtlasRelatedObjectIdAllOf model = new JsonAtlasRelatedObjectIdAllOf();

    /**
     * Model tests for JsonAtlasRelatedObjectIdAllOf
     */
    @Test
    public void testJsonAtlasRelatedObjectIdAllOf() {
        // TODO: test JsonAtlasRelatedObjectIdAllOf
    }

    /**
     * Test the property 'displayText'
     */
    @Test
    public void displayTextTest() {
        // TODO: test displayText
    }

    /**
     * Test the property 'entityStatus'
     */
    @Test
    public void entityStatusTest() {
        // TODO: test entityStatus
    }

    /**
     * Test the property 'relationshipAttributes'
     */
    @Test
    public void relationshipAttributesTest() {
        // TODO: test relationshipAttributes
    }

    /**
     * Test the property 'relationshipGuid'
     */
    @Test
    public void relationshipGuidTest() {
        // TODO: test relationshipGuid
    }

    /**
     * Test the property 'relationshipStatus'
     */
    @Test
    public void relationshipStatusTest() {
        // TODO: test relationshipStatus
    }

}
