/*
 * Purview Catalog Service REST API Document
 * Purview Catalog Service is a fully managed cloud service whose users can discover the data sources they need and understand the data sources they find. At the same time, Data Catalog helps organizations get more value from their existing investments. This swagger defines REST API of the Hot Tier of Data Catalog Gen 2.
 *
 * The version of the OpenAPI document: 2020-12-01-preview
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.client.model.JsonAtlasEntitiesWithExtInfoAllOf;
import org.openapitools.client.model.JsonAtlasEntity;
import org.openapitools.client.model.JsonAtlasEntityExtInfo;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for JsonAtlasEntitiesWithExtInfo
 */
public class JsonAtlasEntitiesWithExtInfoTest {
    private final JsonAtlasEntitiesWithExtInfo model = new JsonAtlasEntitiesWithExtInfo();

    /**
     * Model tests for JsonAtlasEntitiesWithExtInfo
     */
    @Test
    public void testJsonAtlasEntitiesWithExtInfo() {
        // TODO: test JsonAtlasEntitiesWithExtInfo
    }

    /**
     * Test the property 'referredEntities'
     */
    @Test
    public void referredEntitiesTest() {
        // TODO: test referredEntities
    }

    /**
     * Test the property 'entities'
     */
    @Test
    public void entitiesTest() {
        // TODO: test entities
    }

}
