/*
 * Purview Catalog Service REST API Document
 * Purview Catalog Service is a fully managed cloud service whose users can discover the data sources they need and understand the data sources they find. At the same time, Data Catalog helps organizations get more value from their existing investments. This swagger defines REST API of the Hot Tier of Data Catalog Gen 2.
 *
 * The version of the OpenAPI document: 2020-12-01-preview
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.XmlNs0SearchFilterAllOf;
import org.openapitools.client.model.XmlNs0SortType;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for XmlNs0SearchFilter
 */
public class XmlNs0SearchFilterTest {
    private final XmlNs0SearchFilter model = new XmlNs0SearchFilter();

    /**
     * Model tests for XmlNs0SearchFilter
     */
    @Test
    public void testXmlNs0SearchFilter() {
        // TODO: test XmlNs0SearchFilter
    }

    /**
     * Test the property 'getCount'
     */
    @Test
    public void getCountTest() {
        // TODO: test getCount
    }

    /**
     * Test the property 'maxRows'
     */
    @Test
    public void maxRowsTest() {
        // TODO: test maxRows
    }

    /**
     * Test the property 'params'
     */
    @Test
    public void paramsTest() {
        // TODO: test params
    }

    /**
     * Test the property 'sortBy'
     */
    @Test
    public void sortByTest() {
        // TODO: test sortBy
    }

    /**
     * Test the property 'sortType'
     */
    @Test
    public void sortTypeTest() {
        // TODO: test sortType
    }

    /**
     * Test the property 'startIndex'
     */
    @Test
    public void startIndexTest() {
        // TODO: test startIndex
    }

}
