/*
 * Purview Catalog Service REST API Document
 * Purview Catalog Service is a fully managed cloud service whose users can discover the data sources they need and understand the data sources they find. At the same time, Data Catalog helps organizations get more value from their existing investments. This swagger defines REST API of the Hot Tier of Data Catalog Gen 2.
 *
 * The version of the OpenAPI document: 2020-12-01-preview
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * The value item of the autocomplete suggest.
 */
@ApiModel(description = "The value item of the autocomplete suggest.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-01-21T11:36:33.263002+01:00[Europe/Amsterdam]")
public class JsonAutocompleteResultValue {
  public static final String SERIALIZED_NAME_TEXT = "text";
  @SerializedName(SERIALIZED_NAME_TEXT)
  private String text;

  public static final String SERIALIZED_NAME_QUERY_PLUS_TEXT = "queryPlusText";
  @SerializedName(SERIALIZED_NAME_QUERY_PLUS_TEXT)
  private String queryPlusText;


  public JsonAutocompleteResultValue text(String text) {
    
    this.text = text;
    return this;
  }

   /**
   * The completed term or phrase.
   * @return text
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The completed term or phrase.")

  public String getText() {
    return text;
  }


  public void setText(String text) {
    this.text = text;
  }


  public JsonAutocompleteResultValue queryPlusText(String queryPlusText) {
    
    this.queryPlusText = queryPlusText;
    return this;
  }

   /**
   * The completed search query text.
   * @return queryPlusText
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The completed search query text.")

  public String getQueryPlusText() {
    return queryPlusText;
  }


  public void setQueryPlusText(String queryPlusText) {
    this.queryPlusText = queryPlusText;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JsonAutocompleteResultValue jsonAutocompleteResultValue = (JsonAutocompleteResultValue) o;
    return Objects.equals(this.text, jsonAutocompleteResultValue.text) &&
        Objects.equals(this.queryPlusText, jsonAutocompleteResultValue.queryPlusText);
  }

  @Override
  public int hashCode() {
    return Objects.hash(text, queryPlusText);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JsonAutocompleteResultValue {\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    queryPlusText: ").append(toIndentedString(queryPlusText)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

