/*
 * Purview Catalog Service REST API Document
 * Purview Catalog Service is a fully managed cloud service whose users can discover the data sources they need and understand the data sources they find. At the same time, Data Catalog helps organizations get more value from their existing investments. This swagger defines REST API of the Hot Tier of Data Catalog Gen 2.
 *
 * The version of the OpenAPI document: 2020-12-01-preview
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * JsonAtlasEntityDefAllOf
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-01-21T11:36:33.263002+01:00[Europe/Amsterdam]")
public class JsonAtlasEntityDefAllOf {
  public static final String SERIALIZED_NAME_SUB_TYPES = "subTypes";
  @SerializedName(SERIALIZED_NAME_SUB_TYPES)
  private List<String> subTypes = null;

  public static final String SERIALIZED_NAME_SUPER_TYPES = "superTypes";
  @SerializedName(SERIALIZED_NAME_SUPER_TYPES)
  private List<String> superTypes = null;


  public JsonAtlasEntityDefAllOf subTypes(List<String> subTypes) {
    
    this.subTypes = subTypes;
    return this;
  }

  public JsonAtlasEntityDefAllOf addSubTypesItem(String subTypesItem) {
    if (this.subTypes == null) {
      this.subTypes = new ArrayList<String>();
    }
    this.subTypes.add(subTypesItem);
    return this;
  }

   /**
   * An array of sub types.
   * @return subTypes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "An array of sub types.")

  public List<String> getSubTypes() {
    return subTypes;
  }


  public void setSubTypes(List<String> subTypes) {
    this.subTypes = subTypes;
  }


  public JsonAtlasEntityDefAllOf superTypes(List<String> superTypes) {
    
    this.superTypes = superTypes;
    return this;
  }

  public JsonAtlasEntityDefAllOf addSuperTypesItem(String superTypesItem) {
    if (this.superTypes == null) {
      this.superTypes = new ArrayList<String>();
    }
    this.superTypes.add(superTypesItem);
    return this;
  }

   /**
   * An array of super types.
   * @return superTypes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "An array of super types.")

  public List<String> getSuperTypes() {
    return superTypes;
  }


  public void setSuperTypes(List<String> superTypes) {
    this.superTypes = superTypes;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JsonAtlasEntityDefAllOf jsonAtlasEntityDefAllOf = (JsonAtlasEntityDefAllOf) o;
    return Objects.equals(this.subTypes, jsonAtlasEntityDefAllOf.subTypes) &&
        Objects.equals(this.superTypes, jsonAtlasEntityDefAllOf.superTypes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(subTypes, superTypes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JsonAtlasEntityDefAllOf {\n");
    sb.append("    subTypes: ").append(toIndentedString(subTypes)).append("\n");
    sb.append("    superTypes: ").append(toIndentedString(superTypes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

