/*
 * Purview Catalog Service REST API Document
 * Purview Catalog Service is a fully managed cloud service whose users can discover the data sources they need and understand the data sources they find. At the same time, Data Catalog helps organizations get more value from their existing investments. This swagger defines REST API of the Hot Tier of Data Catalog Gen 2.
 *
 * The version of the OpenAPI document: 2020-12-01-preview
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.JsonAtlasBaseModelObject;
import org.openapitools.client.model.JsonAtlasClassification;
import org.openapitools.client.model.JsonAtlasGlossaryBaseObjectAllOf;

/**
 * The glossary base object.
 */
@ApiModel(description = "The glossary base object.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-01-21T11:36:33.263002+01:00[Europe/Amsterdam]")
public class JsonAtlasGlossaryBaseObject {
  public static final String SERIALIZED_NAME_GUID = "guid";
  @SerializedName(SERIALIZED_NAME_GUID)
  private String guid;

  public static final String SERIALIZED_NAME_CLASSIFICATIONS = "classifications";
  @SerializedName(SERIALIZED_NAME_CLASSIFICATIONS)
  private List<JsonAtlasClassification> classifications = null;

  public static final String SERIALIZED_NAME_LONG_DESCRIPTION = "longDescription";
  @SerializedName(SERIALIZED_NAME_LONG_DESCRIPTION)
  private String longDescription;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_QUALIFIED_NAME = "qualifiedName";
  @SerializedName(SERIALIZED_NAME_QUALIFIED_NAME)
  private String qualifiedName;

  public static final String SERIALIZED_NAME_SHORT_DESCRIPTION = "shortDescription";
  @SerializedName(SERIALIZED_NAME_SHORT_DESCRIPTION)
  private String shortDescription;

  public static final String SERIALIZED_NAME_LAST_MODIFIED_T_S = "lastModifiedTS";
  @SerializedName(SERIALIZED_NAME_LAST_MODIFIED_T_S)
  private String lastModifiedTS;


  public JsonAtlasGlossaryBaseObject guid(String guid) {
    
    this.guid = guid;
    return this;
  }

   /**
   * The GUID of the object.
   * @return guid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The GUID of the object.")

  public String getGuid() {
    return guid;
  }


  public void setGuid(String guid) {
    this.guid = guid;
  }


  public JsonAtlasGlossaryBaseObject classifications(List<JsonAtlasClassification> classifications) {
    
    this.classifications = classifications;
    return this;
  }

  public JsonAtlasGlossaryBaseObject addClassificationsItem(JsonAtlasClassification classificationsItem) {
    if (this.classifications == null) {
      this.classifications = new ArrayList<JsonAtlasClassification>();
    }
    this.classifications.add(classificationsItem);
    return this;
  }

   /**
   * An array of classifications.
   * @return classifications
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "An array of classifications.")

  public List<JsonAtlasClassification> getClassifications() {
    return classifications;
  }


  public void setClassifications(List<JsonAtlasClassification> classifications) {
    this.classifications = classifications;
  }


  public JsonAtlasGlossaryBaseObject longDescription(String longDescription) {
    
    this.longDescription = longDescription;
    return this;
  }

   /**
   * The long version description.
   * @return longDescription
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The long version description.")

  public String getLongDescription() {
    return longDescription;
  }


  public void setLongDescription(String longDescription) {
    this.longDescription = longDescription;
  }


  public JsonAtlasGlossaryBaseObject name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * The name of the glossary object.
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The name of the glossary object.")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public JsonAtlasGlossaryBaseObject qualifiedName(String qualifiedName) {
    
    this.qualifiedName = qualifiedName;
    return this;
  }

   /**
   * The qualified name of the glossary object.
   * @return qualifiedName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The qualified name of the glossary object.")

  public String getQualifiedName() {
    return qualifiedName;
  }


  public void setQualifiedName(String qualifiedName) {
    this.qualifiedName = qualifiedName;
  }


  public JsonAtlasGlossaryBaseObject shortDescription(String shortDescription) {
    
    this.shortDescription = shortDescription;
    return this;
  }

   /**
   * The short version of description.
   * @return shortDescription
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The short version of description.")

  public String getShortDescription() {
    return shortDescription;
  }


  public void setShortDescription(String shortDescription) {
    this.shortDescription = shortDescription;
  }


  public JsonAtlasGlossaryBaseObject lastModifiedTS(String lastModifiedTS) {
    
    this.lastModifiedTS = lastModifiedTS;
    return this;
  }

   /**
   * ETag for concurrency control.
   * @return lastModifiedTS
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "ETag for concurrency control.")

  public String getLastModifiedTS() {
    return lastModifiedTS;
  }


  public void setLastModifiedTS(String lastModifiedTS) {
    this.lastModifiedTS = lastModifiedTS;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JsonAtlasGlossaryBaseObject jsonAtlasGlossaryBaseObject = (JsonAtlasGlossaryBaseObject) o;
    return Objects.equals(this.guid, jsonAtlasGlossaryBaseObject.guid) &&
        Objects.equals(this.classifications, jsonAtlasGlossaryBaseObject.classifications) &&
        Objects.equals(this.longDescription, jsonAtlasGlossaryBaseObject.longDescription) &&
        Objects.equals(this.name, jsonAtlasGlossaryBaseObject.name) &&
        Objects.equals(this.qualifiedName, jsonAtlasGlossaryBaseObject.qualifiedName) &&
        Objects.equals(this.shortDescription, jsonAtlasGlossaryBaseObject.shortDescription) &&
        Objects.equals(this.lastModifiedTS, jsonAtlasGlossaryBaseObject.lastModifiedTS);
  }

  @Override
  public int hashCode() {
    return Objects.hash(guid, classifications, longDescription, name, qualifiedName, shortDescription, lastModifiedTS);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JsonAtlasGlossaryBaseObject {\n");
    sb.append("    guid: ").append(toIndentedString(guid)).append("\n");
    sb.append("    classifications: ").append(toIndentedString(classifications)).append("\n");
    sb.append("    longDescription: ").append(toIndentedString(longDescription)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    qualifiedName: ").append(toIndentedString(qualifiedName)).append("\n");
    sb.append("    shortDescription: ").append(toIndentedString(shortDescription)).append("\n");
    sb.append("    lastModifiedTS: ").append(toIndentedString(lastModifiedTS)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

