/*
 * Purview Catalog Service REST API Document
 * Purview Catalog Service is a fully managed cloud service whose users can discover the data sources they need and understand the data sources they find. At the same time, Data Catalog helps organizations get more value from their existing investments. This swagger defines REST API of the Hot Tier of Data Catalog Gen 2.
 *
 * The version of the OpenAPI document: 2020-12-01-preview
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.JsonAtlasEntitiesWithExtInfo;
import org.openapitools.client.model.JsonAtlasObjectId;
import org.openapitools.client.model.JsonHookNotificationType;

/**
 * The class for hook notification for type ENTITY_PARTIAL_UPDATE_V2.
 */
@ApiModel(description = "The class for hook notification for type ENTITY_PARTIAL_UPDATE_V2.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-01-21T11:36:33.263002+01:00[Europe/Amsterdam]")
public class JsonEntityPartialUpdateRequestV2 {
  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private JsonHookNotificationType type;

  public static final String SERIALIZED_NAME_USER = "user";
  @SerializedName(SERIALIZED_NAME_USER)
  private String user = "UNKNOWN";

  public static final String SERIALIZED_NAME_ENTITY_ID = "entityId";
  @SerializedName(SERIALIZED_NAME_ENTITY_ID)
  private JsonAtlasObjectId entityId;

  public static final String SERIALIZED_NAME_ENTITY = "entity";
  @SerializedName(SERIALIZED_NAME_ENTITY)
  private JsonAtlasEntitiesWithExtInfo entity = null;


  public JsonEntityPartialUpdateRequestV2 type(JsonHookNotificationType type) {
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public JsonHookNotificationType getType() {
    return type;
  }


  public void setType(JsonHookNotificationType type) {
    this.type = type;
  }


  public JsonEntityPartialUpdateRequestV2 user(String user) {
    
    this.user = user;
    return this;
  }

   /**
   * The user of the notification. Default to be \&quot;UNKNOWN\&quot;.
   * @return user
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The user of the notification. Default to be \"UNKNOWN\".")

  public String getUser() {
    return user;
  }


  public void setUser(String user) {
    this.user = user;
  }


  public JsonEntityPartialUpdateRequestV2 entityId(JsonAtlasObjectId entityId) {
    
    this.entityId = entityId;
    return this;
  }

   /**
   * Get entityId
   * @return entityId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public JsonAtlasObjectId getEntityId() {
    return entityId;
  }


  public void setEntityId(JsonAtlasObjectId entityId) {
    this.entityId = entityId;
  }


  public JsonEntityPartialUpdateRequestV2 entity(JsonAtlasEntitiesWithExtInfo entity) {
    
    this.entity = entity;
    return this;
  }

   /**
   * Get entity
   * @return entity
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public JsonAtlasEntitiesWithExtInfo getEntity() {
    return entity;
  }


  public void setEntity(JsonAtlasEntitiesWithExtInfo entity) {
    this.entity = entity;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JsonEntityPartialUpdateRequestV2 jsonEntityPartialUpdateRequestV2 = (JsonEntityPartialUpdateRequestV2) o;
    return Objects.equals(this.type, jsonEntityPartialUpdateRequestV2.type) &&
        Objects.equals(this.user, jsonEntityPartialUpdateRequestV2.user) &&
        Objects.equals(this.entityId, jsonEntityPartialUpdateRequestV2.entityId) &&
        Objects.equals(this.entity, jsonEntityPartialUpdateRequestV2.entity);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, user, entityId, entity);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JsonEntityPartialUpdateRequestV2 {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("    entityId: ").append(toIndentedString(entityId)).append("\n");
    sb.append("    entity: ").append(toIndentedString(entity)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

