/*
 * Purview Catalog Service REST API Document
 * Purview Catalog Service is a fully managed cloud service whose users can discover the data sources they need and understand the data sources they find. At the same time, Data Catalog helps organizations get more value from their existing investments. This swagger defines REST API of the Hot Tier of Data Catalog Gen 2.
 *
 * The version of the OpenAPI document: 2020-12-01-preview
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * The context.
 */
@ApiModel(description = "The context.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-01-21T11:36:33.263002+01:00[Europe/Amsterdam]")
public class JsonTermSearchResultValue {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_GLOSSARY_NAME = "glossaryName";
  @SerializedName(SERIALIZED_NAME_GLOSSARY_NAME)
  private String glossaryName;


  public JsonTermSearchResultValue name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * The name of the term.
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The name of the term.")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public JsonTermSearchResultValue glossaryName(String glossaryName) {
    
    this.glossaryName = glossaryName;
    return this;
  }

   /**
   * The name of the glossary which contains the term.
   * @return glossaryName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The name of the glossary which contains the term.")

  public String getGlossaryName() {
    return glossaryName;
  }


  public void setGlossaryName(String glossaryName) {
    this.glossaryName = glossaryName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JsonTermSearchResultValue jsonTermSearchResultValue = (JsonTermSearchResultValue) o;
    return Objects.equals(this.name, jsonTermSearchResultValue.name) &&
        Objects.equals(this.glossaryName, jsonTermSearchResultValue.glossaryName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, glossaryName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JsonTermSearchResultValue {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    glossaryName: ").append(toIndentedString(glossaryName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

