/*
 * Purview Catalog Service REST API Document
 * Purview Catalog Service is a fully managed cloud service whose users can discover the data sources they need and understand the data sources they find. At the same time, Data Catalog helps organizations get more value from their existing investments. This swagger defines REST API of the Hot Tier of Data Catalog Gen 2.
 *
 * The version of the OpenAPI document: 2020-12-01-preview
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Supported search operations Logical comparision operators can only be used with numbers or dates IN, LIKE, startsWith, endsWith, CONTAINS can only be used with strings or text
 */
@JsonAdapter(JsonOperator.Adapter.class)
public enum JsonOperator {
  
  LT("LT"),
  
  GT("GT"),
  
  LTE("LTE"),
  
  GTE("GTE"),
  
  EQ("EQ"),
  
  NEQ("NEQ"),
  
  IN("IN"),
  
  LIKE("LIKE"),
  
  STARTS_WITH("STARTS_WITH"),
  
  ENDS_WITH("ENDS_WITH"),
  
  CONTAINS("CONTAINS"),
  
  CONTAINS_ANY("CONTAINS_ANY"),
  
  CONTAINS_ALL("CONTAINS_ALL"),
  
  IS_NULL("IS_NULL"),
  
  NOT_NULL("NOT_NULL");

  private String value;

  JsonOperator(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static JsonOperator fromValue(String value) {
    for (JsonOperator b : JsonOperator.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<JsonOperator> {
    @Override
    public void write(final JsonWriter jsonWriter, final JsonOperator enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public JsonOperator read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return JsonOperator.fromValue(value);
    }
  }
}

