/*
 * Purview Catalog Service REST API Document
 * Purview Catalog Service is a fully managed cloud service whose users can discover the data sources they need and understand the data sources they find. At the same time, Data Catalog helps organizations get more value from their existing investments. This swagger defines REST API of the Hot Tier of Data Catalog Gen 2.
 *
 * The version of the OpenAPI document: 2020-12-01-preview
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * A highlight list that consists of index fields id ,qualifiedName, name, description, entityType. When the keyword appears in those fields, the value of the field, attached with emphasis mark, is returned as an element of @search.highlights.
 */
@ApiModel(description = "A highlight list that consists of index fields id ,qualifiedName, name, description, entityType. When the keyword appears in those fields, the value of the field, attached with emphasis mark, is returned as an element of @search.highlights.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-01-21T11:36:33.263002+01:00[Europe/Amsterdam]")
public class JsonSearchHighlights {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private List<String> id = null;

  public static final String SERIALIZED_NAME_QUALIFIED_NAME = "qualifiedName";
  @SerializedName(SERIALIZED_NAME_QUALIFIED_NAME)
  private List<String> qualifiedName = null;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private List<String> name = null;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private List<String> description = null;

  public static final String SERIALIZED_NAME_ENTITY_TYPE = "entityType";
  @SerializedName(SERIALIZED_NAME_ENTITY_TYPE)
  private List<String> entityType = null;


  public JsonSearchHighlights id(List<String> id) {
    
    this.id = id;
    return this;
  }

  public JsonSearchHighlights addIdItem(String idItem) {
    if (this.id == null) {
      this.id = new ArrayList<String>();
    }
    this.id.add(idItem);
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getId() {
    return id;
  }


  public void setId(List<String> id) {
    this.id = id;
  }


  public JsonSearchHighlights qualifiedName(List<String> qualifiedName) {
    
    this.qualifiedName = qualifiedName;
    return this;
  }

  public JsonSearchHighlights addQualifiedNameItem(String qualifiedNameItem) {
    if (this.qualifiedName == null) {
      this.qualifiedName = new ArrayList<String>();
    }
    this.qualifiedName.add(qualifiedNameItem);
    return this;
  }

   /**
   * Get qualifiedName
   * @return qualifiedName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getQualifiedName() {
    return qualifiedName;
  }


  public void setQualifiedName(List<String> qualifiedName) {
    this.qualifiedName = qualifiedName;
  }


  public JsonSearchHighlights name(List<String> name) {
    
    this.name = name;
    return this;
  }

  public JsonSearchHighlights addNameItem(String nameItem) {
    if (this.name == null) {
      this.name = new ArrayList<String>();
    }
    this.name.add(nameItem);
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getName() {
    return name;
  }


  public void setName(List<String> name) {
    this.name = name;
  }


  public JsonSearchHighlights description(List<String> description) {
    
    this.description = description;
    return this;
  }

  public JsonSearchHighlights addDescriptionItem(String descriptionItem) {
    if (this.description == null) {
      this.description = new ArrayList<String>();
    }
    this.description.add(descriptionItem);
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getDescription() {
    return description;
  }


  public void setDescription(List<String> description) {
    this.description = description;
  }


  public JsonSearchHighlights entityType(List<String> entityType) {
    
    this.entityType = entityType;
    return this;
  }

  public JsonSearchHighlights addEntityTypeItem(String entityTypeItem) {
    if (this.entityType == null) {
      this.entityType = new ArrayList<String>();
    }
    this.entityType.add(entityTypeItem);
    return this;
  }

   /**
   * Get entityType
   * @return entityType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getEntityType() {
    return entityType;
  }


  public void setEntityType(List<String> entityType) {
    this.entityType = entityType;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JsonSearchHighlights jsonSearchHighlights = (JsonSearchHighlights) o;
    return Objects.equals(this.id, jsonSearchHighlights.id) &&
        Objects.equals(this.qualifiedName, jsonSearchHighlights.qualifiedName) &&
        Objects.equals(this.name, jsonSearchHighlights.name) &&
        Objects.equals(this.description, jsonSearchHighlights.description) &&
        Objects.equals(this.entityType, jsonSearchHighlights.entityType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, qualifiedName, name, description, entityType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JsonSearchHighlights {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    qualifiedName: ").append(toIndentedString(qualifiedName)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    entityType: ").append(toIndentedString(entityType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

