/*
 * Purview Catalog Service REST API Document
 * Purview Catalog Service is a fully managed cloud service whose users can discover the data sources they need and understand the data sources they find. At the same time, Data Catalog helps organizations get more value from their existing investments. This swagger defines REST API of the Hot Tier of Data Catalog Gen 2.
 *
 * The version of the OpenAPI document: 2020-12-01-preview
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Request for catalog deletion.
 */
@ApiModel(description = "Request for catalog deletion.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-01-21T11:36:33.263002+01:00[Europe/Amsterdam]")
public class JsonCatalogDeletionRequest {
  public static final String SERIALIZED_NAME_CATALOG_NAME = "catalogName";
  @SerializedName(SERIALIZED_NAME_CATALOG_NAME)
  private String catalogName;


  public JsonCatalogDeletionRequest catalogName(String catalogName) {
    
    this.catalogName = catalogName;
    return this;
  }

   /**
   * Name of the catalog.
   * @return catalogName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Name of the catalog.")

  public String getCatalogName() {
    return catalogName;
  }


  public void setCatalogName(String catalogName) {
    this.catalogName = catalogName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JsonCatalogDeletionRequest jsonCatalogDeletionRequest = (JsonCatalogDeletionRequest) o;
    return Objects.equals(this.catalogName, jsonCatalogDeletionRequest.catalogName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(catalogName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JsonCatalogDeletionRequest {\n");
    sb.append("    catalogName: ").append(toIndentedString(catalogName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

