/*
 * Purview Catalog Service REST API Document
 * Purview Catalog Service is a fully managed cloud service whose users can discover the data sources they need and understand the data sources they find. At the same time, Data Catalog helps organizations get more value from their existing investments. This swagger defines REST API of the Hot Tier of Data Catalog Gen 2.
 *
 * The version of the OpenAPI document: 2020-12-01-preview
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.client.model.JsonAtlasEntitiesWithExtInfoAllOf;
import org.openapitools.client.model.JsonAtlasEntity;
import org.openapitools.client.model.JsonAtlasEntityExtInfo;

/**
 * An instance of an entity along with extended info - like hive_table, hive_database.
 */
@ApiModel(description = "An instance of an entity along with extended info - like hive_table, hive_database.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-01-21T11:36:33.263002+01:00[Europe/Amsterdam]")
public class JsonAtlasEntitiesWithExtInfo {
  public static final String SERIALIZED_NAME_REFERRED_ENTITIES = "referredEntities";
  @SerializedName(SERIALIZED_NAME_REFERRED_ENTITIES)
  private Map<String, JsonAtlasEntity> referredEntities = null;

  public static final String SERIALIZED_NAME_ENTITIES = "entities";
  @SerializedName(SERIALIZED_NAME_ENTITIES)
  private List<JsonAtlasEntity> entities = null;


  public JsonAtlasEntitiesWithExtInfo referredEntities(Map<String, JsonAtlasEntity> referredEntities) {
    
    this.referredEntities = referredEntities;
    return this;
  }

  public JsonAtlasEntitiesWithExtInfo putReferredEntitiesItem(String key, JsonAtlasEntity referredEntitiesItem) {
    if (this.referredEntities == null) {
      this.referredEntities = new HashMap<String, JsonAtlasEntity>();
    }
    this.referredEntities.put(key, referredEntitiesItem);
    return this;
  }

   /**
   * The referred entities.
   * @return referredEntities
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The referred entities.")

  public Map<String, JsonAtlasEntity> getReferredEntities() {
    return referredEntities;
  }


  public void setReferredEntities(Map<String, JsonAtlasEntity> referredEntities) {
    this.referredEntities = referredEntities;
  }


  public JsonAtlasEntitiesWithExtInfo entities(List<JsonAtlasEntity> entities) {
    
    this.entities = entities;
    return this;
  }

  public JsonAtlasEntitiesWithExtInfo addEntitiesItem(JsonAtlasEntity entitiesItem) {
    if (this.entities == null) {
      this.entities = new ArrayList<JsonAtlasEntity>();
    }
    this.entities.add(entitiesItem);
    return this;
  }

   /**
   * An array of entities.
   * @return entities
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "An array of entities.")

  public List<JsonAtlasEntity> getEntities() {
    return entities;
  }


  public void setEntities(List<JsonAtlasEntity> entities) {
    this.entities = entities;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JsonAtlasEntitiesWithExtInfo jsonAtlasEntitiesWithExtInfo = (JsonAtlasEntitiesWithExtInfo) o;
    return Objects.equals(this.referredEntities, jsonAtlasEntitiesWithExtInfo.referredEntities) &&
        Objects.equals(this.entities, jsonAtlasEntitiesWithExtInfo.entities);
  }

  @Override
  public int hashCode() {
    return Objects.hash(referredEntities, entities);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JsonAtlasEntitiesWithExtInfo {\n");
    sb.append("    referredEntities: ").append(toIndentedString(referredEntities)).append("\n");
    sb.append("    entities: ").append(toIndentedString(entities)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

