/*
 * Purview Catalog Service REST API Document
 * Purview Catalog Service is a fully managed cloud service whose users can discover the data sources they need and understand the data sources they find. At the same time, Data Catalog helps organizations get more value from their existing investments. This swagger defines REST API of the Hot Tier of Data Catalog Gen 2.
 *
 * The version of the OpenAPI document: 2020-12-01-preview
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.JsonSearchFacetResultValue;
import org.openapitools.client.model.JsonSearchResultValue;

/**
 * The result of the advanced search result.
 */
@ApiModel(description = "The result of the advanced search result.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-01-21T11:36:33.263002+01:00[Europe/Amsterdam]")
public class JsonAdvancedSearchResult {
  public static final String SERIALIZED_NAME_AT_SEARCH_COUNT = "@search.count";
  @SerializedName(SERIALIZED_NAME_AT_SEARCH_COUNT)
  private Integer atSearchCount;

  public static final String SERIALIZED_NAME_AT_SEARCH_FACETS = "@search.facets";
  @SerializedName(SERIALIZED_NAME_AT_SEARCH_FACETS)
  private JsonSearchFacetResultValue atSearchFacets;

  public static final String SERIALIZED_NAME_VALUE = "value";
  @SerializedName(SERIALIZED_NAME_VALUE)
  private List<JsonSearchResultValue> value = null;


  public JsonAdvancedSearchResult atSearchCount(Integer atSearchCount) {
    
    this.atSearchCount = atSearchCount;
    return this;
  }

   /**
   * The total number of search results (not the number of documents in a single page).
   * @return atSearchCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The total number of search results (not the number of documents in a single page).")

  public Integer getAtSearchCount() {
    return atSearchCount;
  }


  public void setAtSearchCount(Integer atSearchCount) {
    this.atSearchCount = atSearchCount;
  }


  public JsonAdvancedSearchResult atSearchFacets(JsonSearchFacetResultValue atSearchFacets) {
    
    this.atSearchFacets = atSearchFacets;
    return this;
  }

   /**
   * Get atSearchFacets
   * @return atSearchFacets
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public JsonSearchFacetResultValue getAtSearchFacets() {
    return atSearchFacets;
  }


  public void setAtSearchFacets(JsonSearchFacetResultValue atSearchFacets) {
    this.atSearchFacets = atSearchFacets;
  }


  public JsonAdvancedSearchResult value(List<JsonSearchResultValue> value) {
    
    this.value = value;
    return this;
  }

  public JsonAdvancedSearchResult addValueItem(JsonSearchResultValue valueItem) {
    if (this.value == null) {
      this.value = new ArrayList<JsonSearchResultValue>();
    }
    this.value.add(valueItem);
    return this;
  }

   /**
   * Get value
   * @return value
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<JsonSearchResultValue> getValue() {
    return value;
  }


  public void setValue(List<JsonSearchResultValue> value) {
    this.value = value;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JsonAdvancedSearchResult jsonAdvancedSearchResult = (JsonAdvancedSearchResult) o;
    return Objects.equals(this.atSearchCount, jsonAdvancedSearchResult.atSearchCount) &&
        Objects.equals(this.atSearchFacets, jsonAdvancedSearchResult.atSearchFacets) &&
        Objects.equals(this.value, jsonAdvancedSearchResult.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(atSearchCount, atSearchFacets, value);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JsonAdvancedSearchResult {\n");
    sb.append("    atSearchCount: ").append(toIndentedString(atSearchCount)).append("\n");
    sb.append("    atSearchFacets: ").append(toIndentedString(atSearchFacets)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

