/*
 * Purview Catalog Service REST API Document
 * Purview Catalog Service is a fully managed cloud service whose users can discover the data sources they need and understand the data sources they find. At the same time, Data Catalog helps organizations get more value from their existing investments. This swagger defines REST API of the Hot Tier of Data Catalog Gen 2.
 *
 * The version of the OpenAPI document: 2020-12-01-preview
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * JsonImportCSVOperationProperties
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-01-21T11:36:33.263002+01:00[Europe/Amsterdam]")
public class JsonImportCSVOperationProperties {
  public static final String SERIALIZED_NAME_IMPORTED_TERMS = "importedTerms";
  @SerializedName(SERIALIZED_NAME_IMPORTED_TERMS)
  private BigDecimal importedTerms;

  public static final String SERIALIZED_NAME_TOTAL_TERMS_DETECT = "totalTermsDetect";
  @SerializedName(SERIALIZED_NAME_TOTAL_TERMS_DETECT)
  private BigDecimal totalTermsDetect;


  public JsonImportCSVOperationProperties importedTerms(BigDecimal importedTerms) {
    
    this.importedTerms = importedTerms;
    return this;
  }

   /**
   * Term numbers that already imported successfully
   * @return importedTerms
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Term numbers that already imported successfully")

  public BigDecimal getImportedTerms() {
    return importedTerms;
  }


  public void setImportedTerms(BigDecimal importedTerms) {
    this.importedTerms = importedTerms;
  }


  public JsonImportCSVOperationProperties totalTermsDetect(BigDecimal totalTermsDetect) {
    
    this.totalTermsDetect = totalTermsDetect;
    return this;
  }

   /**
   * Total term numbers that detected in csv
   * @return totalTermsDetect
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Total term numbers that detected in csv")

  public BigDecimal getTotalTermsDetect() {
    return totalTermsDetect;
  }


  public void setTotalTermsDetect(BigDecimal totalTermsDetect) {
    this.totalTermsDetect = totalTermsDetect;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JsonImportCSVOperationProperties jsonImportCSVOperationProperties = (JsonImportCSVOperationProperties) o;
    return Objects.equals(this.importedTerms, jsonImportCSVOperationProperties.importedTerms) &&
        Objects.equals(this.totalTermsDetect, jsonImportCSVOperationProperties.totalTermsDetect);
  }

  @Override
  public int hashCode() {
    return Objects.hash(importedTerms, totalTermsDetect);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JsonImportCSVOperationProperties {\n");
    sb.append("    importedTerms: ").append(toIndentedString(importedTerms)).append("\n");
    sb.append("    totalTermsDetect: ").append(toIndentedString(totalTermsDetect)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

