/*
 * Purview Catalog Service REST API Document
 * Purview Catalog Service is a fully managed cloud service whose users can discover the data sources they need and understand the data sources they find. At the same time, Data Catalog helps organizations get more value from their existing investments. This swagger defines REST API of the Hot Tier of Data Catalog Gen 2.
 *
 * The version of the OpenAPI document: 2020-12-01-preview
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.client.model.JsonAtlasEntityHeader;

/**
 * An instance of an entity header.
 */
@ApiModel(description = "An instance of an entity header.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-01-21T11:36:33.263002+01:00[Europe/Amsterdam]")
public class JsonAtlasEntityHeaders {
  public static final String SERIALIZED_NAME_GUID_HEADER_MAP = "guidHeaderMap";
  @SerializedName(SERIALIZED_NAME_GUID_HEADER_MAP)
  private Map<String, JsonAtlasEntityHeader> guidHeaderMap = null;


  public JsonAtlasEntityHeaders guidHeaderMap(Map<String, JsonAtlasEntityHeader> guidHeaderMap) {
    
    this.guidHeaderMap = guidHeaderMap;
    return this;
  }

  public JsonAtlasEntityHeaders putGuidHeaderMapItem(String key, JsonAtlasEntityHeader guidHeaderMapItem) {
    if (this.guidHeaderMap == null) {
      this.guidHeaderMap = new HashMap<String, JsonAtlasEntityHeader>();
    }
    this.guidHeaderMap.put(key, guidHeaderMapItem);
    return this;
  }

   /**
   * 
   * @return guidHeaderMap
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Map<String, JsonAtlasEntityHeader> getGuidHeaderMap() {
    return guidHeaderMap;
  }


  public void setGuidHeaderMap(Map<String, JsonAtlasEntityHeader> guidHeaderMap) {
    this.guidHeaderMap = guidHeaderMap;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JsonAtlasEntityHeaders jsonAtlasEntityHeaders = (JsonAtlasEntityHeaders) o;
    return Objects.equals(this.guidHeaderMap, jsonAtlasEntityHeaders.guidHeaderMap);
  }

  @Override
  public int hashCode() {
    return Objects.hash(guidHeaderMap);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JsonAtlasEntityHeaders {\n");
    sb.append("    guidHeaderMap: ").append(toIndentedString(guidHeaderMap)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

