/*
 * Purview Catalog Service REST API Document
 * Purview Catalog Service is a fully managed cloud service whose users can discover the data sources they need and understand the data sources they find. At the same time, Data Catalog helps organizations get more value from their existing investments. This swagger defines REST API of the Hot Tier of Data Catalog Gen 2.
 *
 * The version of the OpenAPI document: 2020-12-01-preview
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * to specify whether the result should be sorted? If yes, whether asc or desc.
 */
@JsonAdapter(XmlNs0SortType.Adapter.class)
public enum XmlNs0SortType {
  
  NONE("NONE"),
  
  ASC("ASC"),
  
  DESC("DESC");

  private String value;

  XmlNs0SortType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static XmlNs0SortType fromValue(String value) {
    for (XmlNs0SortType b : XmlNs0SortType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<XmlNs0SortType> {
    @Override
    public void write(final JsonWriter jsonWriter, final XmlNs0SortType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public XmlNs0SortType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return XmlNs0SortType.fromValue(value);
    }
  }
}

